"""pivot_general_wiki_pages

Revision ID: 120ffbbffa7c
Revises: 030
Create Date: 2026-05-31 19:37:31.005749
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = '120ffbbffa7c'
down_revision: Union[str, None] = '030'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wiki_pages', sa.Column('status', sa.String(length=20), nullable=False, server_default='seed', comment='Lifecycle status: seed | developing | mature | evergreen'))
    op.drop_index('ix_wiki_pages_page_type', table_name='wiki_pages')
    op.create_index('ix_wiki_pages_status', 'wiki_pages', ['status'], unique=False)
    op.drop_column('wiki_pages', 'page_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wiki_pages', sa.Column('page_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False, server_default='concept'))
    op.drop_index('ix_wiki_pages_status', table_name='wiki_pages')
    op.create_index('ix_wiki_pages_page_type', 'wiki_pages', ['page_type'], unique=False)
    op.drop_column('wiki_pages', 'status')
    # ### end Alembic commands ###
